In [1]:
import pymysql.cursors
con = pymysql.connect(host = 'localhost', 
                            user = 'root',
                            password = 'root',
                            db = 'swyoo',
                            charset = 'utf8mb4')

In [2]:
cursor = con.cursor()

In [3]:
sql = "select * from wiki"
cursor.execute(sql)

500

In [4]:
result_wiki = cursor.fetchall()

In [5]:
result_wiki[0]

(24031233,
 'Sue_Medley',
 "Sue Medley.Susan Gayle Sue Medley (born 1962 at Courtenay, British Columbia) is a Canadian rock musician. She released her self-titled debut CD in 1990. She won a Juno Award in 1991 for Most Promising Female Vocalist.Early years.A native of Vancouver Island, British Columbia, Canada, Sue Medley was signed to Polygram Records Canada in 1989 and released a self-titled debut CD in 1990. The album was co-produced by Medley and John Mellencamp producer Michael Wanchic and featured strong performances by John Hiatt's band The Goners. In Canada Medley's first single, Dangerous Times not only pushed her debut album to gold status within a few weeks of release, but was #1 on MuchMusic for two weeks, #1 on the Pop Adult charts for 12 weeks, in the Top 3 of the national album rock chart for six weeks, and earned her a SOCAN Songwriter of the Year Award for most airplay.On the heels of the singles Dangerous Times, Maybe the Next Time, Thats Life, and Love Thing, she toured North America the rest of the year opening for Bob Dylan and other high profile artists. Her second album, Inside Out, was once again co-produced by Medley and Wanchic and was aided by the musical help of slide guitarist Sonny Landreth and drummer Kenny Aronoff. The album, released in 1992, continued her radio success with a handful of additional singles and national tours with such artists as Tom Cochrane, Kim Mitchell and 54.40, keeping her in the spotlight. The first single When the Stars Fall became a hit on album radio and reached #2 on The Records chart (being locked out of #1 only by U2). In October 1992 she was invited by John Mellencamp to participate in the Bob Dylan Tribute at Madison Square Gardens in New York City, and performed a duet with Mellencamp on the classic Dylan track Like a Rolling Stone. Later that month she received a SOCAN award for her song Maybe the Next Time, which was one of the most played songs on Canadian radio in 1991.Dispute with Polygram.Her third album, however, would not be forthcoming. Following a two-year dispute with her record label over the songs that would comprise that release, she and Polygram parted ways. She retreated to her house near Bloomington, Indiana, and wrote and recorded much of the material that made up her independent release, Velvet Morning, which was released in February 2000 on Egg Records. Her profile received a boost after four of her songs were featured on the TV series Dawson's Creek.Recent activity.After the renewal of her profile with Dawson's Creek, Medley lived and worked in Los Angeles, teaching guitar and helping to develop a new generation of budding songwriters and recording artists. Medley recently returned to Canada, and is now writing and demoing new material for an upcoming release. She is currently represented by Inner Circle Management, an art and cultural industries consulting business, based in Regina, Saskatchewan. In 2011 she joined the horn driven band Time Well Wasted based in her home town of Courtenay, British Columbia. After two years, Medley left TWW to form her own band Sue Medley & The Back Road Band, and in July 2013 released the 3-song EP Sue Medley & The Back Road Band, and followed this with a full length album These Are The Days, both productions co-produced with former CBC Music Producer / Recording Engineer John Mang. Sue Medley continues to perform, teach and perform in the Comox Valley.")

In [6]:
import nltk
# nltk.download('punkt')
tokens = nltk.word_tokenize(result_wiki[0][2])
tokens

['Sue',
 'Medley.Susan',
 'Gayle',
 'Sue',
 'Medley',
 '(',
 'born',
 '1962',
 'at',
 'Courtenay',
 ',',
 'British',
 'Columbia',
 ')',
 'is',
 'a',
 'Canadian',
 'rock',
 'musician',
 '.',
 'She',
 'released',
 'her',
 'self-titled',
 'debut',
 'CD',
 'in',
 '1990',
 '.',
 'She',
 'won',
 'a',
 'Juno',
 'Award',
 'in',
 '1991',
 'for',
 'Most',
 'Promising',
 'Female',
 'Vocalist.Early',
 'years.A',
 'native',
 'of',
 'Vancouver',
 'Island',
 ',',
 'British',
 'Columbia',
 ',',
 'Canada',
 ',',
 'Sue',
 'Medley',
 'was',
 'signed',
 'to',
 'Polygram',
 'Records',
 'Canada',
 'in',
 '1989',
 'and',
 'released',
 'a',
 'self-titled',
 'debut',
 'CD',
 'in',
 '1990',
 '.',
 'The',
 'album',
 'was',
 'co-produced',
 'by',
 'Medley',
 'and',
 'John',
 'Mellencamp',
 'producer',
 'Michael',
 'Wanchic',
 'and',
 'featured',
 'strong',
 'performances',
 'by',
 'John',
 'Hiatt',
 "'s",
 'band',
 'The',
 'Goners',
 '.',
 'In',
 'Canada',
 'Medley',
 "'s",
 'first',
 'single',
 ',',
 'Dangerous',
 'Times',
 'not',
 'only',
 'pushed',
 'her',
 'debut',
 'album',
 'to',
 'gold',
 'status',
 'within',
 'a',
 'few',
 'weeks',
 'of',
 'release',
 ',',
 'but',
 'was',
 '#',
 '1',
 'on',
 'MuchMusic',
 'for',
 'two',
 'weeks',
 ',',
 '#',
 '1',
 'on',
 'the',
 'Pop',
 'Adult',
 'charts',
 'for',
 '12',
 'weeks',
 ',',
 'in',
 'the',
 'Top',
 '3',
 'of',
 'the',
 'national',
 'album',
 'rock',
 'chart',
 'for',
 'six',
 'weeks',
 ',',
 'and',
 'earned',
 'her',
 'a',
 'SOCAN',
 'Songwriter',
 'of',
 'the',
 'Year',
 'Award',
 'for',
 'most',
 'airplay.On',
 'the',
 'heels',
 'of',
 'the',
 'singles',
 'Dangerous',
 'Times',
 ',',
 'Maybe',
 'the',
 'Next',
 'Time',
 ',',
 'Thats',
 'Life',
 ',',
 'and',
 'Love',
 'Thing',
 ',',
 'she',
 'toured',
 'North',
 'America',
 'the',
 'rest',
 'of',
 'the',
 'year',
 'opening',
 'for',
 'Bob',
 'Dylan',
 'and',
 'other',
 'high',
 'profile',
 'artists',
 '.',
 'Her',
 'second',
 'album',
 ',',
 'Inside',
 'Out',
 ',',
 'was',
 'once',
 'again',
 'co-produced',
 'by',
 'Medley',
 'and',
 'Wanchic',
 'and',
 'was',
 'aided',
 'by',
 'the',
 'musical',
 'help',
 'of',
 'slide',
 'guitarist',
 'Sonny',
 'Landreth',
 'and',
 'drummer',
 'Kenny',
 'Aronoff',
 '.',
 'The',
 'album',
 ',',
 'released',
 'in',
 '1992',
 ',',
 'continued',
 'her',
 'radio',
 'success',
 'with',
 'a',
 'handful',
 'of',
 'additional',
 'singles',
 'and',
 'national',
 'tours',
 'with',
 'such',
 'artists',
 'as',
 'Tom',
 'Cochrane',
 ',',
 'Kim',
 'Mitchell',
 'and',
 '54.40',
 ',',
 'keeping',
 'her',
 'in',
 'the',
 'spotlight',
 '.',
 'The',
 'first',
 'single',
 'When',
 'the',
 'Stars',
 'Fall',
 'became',
 'a',
 'hit',
 'on',
 'album',
 'radio',
 'and',
 'reached',
 '#',
 '2',
 'on',
 'The',
 'Records',
 'chart',
 '(',
 'being',
 'locked',
 'out',
 'of',
 '#',
 '1',
 'only',
 'by',
 'U2',
 ')',
 '.',
 'In',
 'October',
 '1992',
 'she',
 'was',
 'invited',
 'by',
 'John',
 'Mellencamp',
 'to',
 'participate',
 'in',
 'the',
 'Bob',
 'Dylan',
 'Tribute',
 'at',
 'Madison',
 'Square',
 'Gardens',
 'in',
 'New',
 'York',
 'City',
 ',',
 'and',
 'performed',
 'a',
 'duet',
 'with',
 'Mellencamp',
 'on',
 'the',
 'classic',
 'Dylan',
 'track',
 'Like',
 'a',
 'Rolling',
 'Stone',
 '.',
 'Later',
 'that',
 'month',
 'she',
 'received',
 'a',
 'SOCAN',
 'award',
 'for',
 'her',
 'song',
 'Maybe',
 'the',
 'Next',
 'Time',
 ',',
 'which',
 'was',
 'one',
 'of',
 'the',
 'most',
 'played',
 'songs',
 'on',
 'Canadian',
 'radio',
 'in',
 '1991.Dispute',
 'with',
 'Polygram.Her',
 'third',
 'album',
 ',',
 'however',
 ',',
 'would',
 'not',
 'be',
 'forthcoming',
 '.',
 'Following',
 'a',
 'two-year',
 'dispute',
 'with',
 'her',
 'record',
 'label',
 'over',
 'the',
 'songs',
 'that',
 'would',
 'comprise',
 'that',
 'release',
 ',',
 'she',
 'and',
 'Polygram',
 'parted',
 'ways',
 '.',
 'She',
 'retreated',
 'to',
 'her',
 'house',
 'near',
 'Bloomington',
 ',',
 'Indiana',
 ',',
 'and',
 'wrote',
 'and',
 'recorded',
 'much',
 'of',
 'the',
 'material',
 'that',
 'made',
 'up',
 'her',
 'independent',
 'release',
 ',',
 'Velvet',
 'Morning',
 ',',
 'which',
 'was',
 'released',
 'in',
 'February',
 '2000',
 'on',
 'Egg',
 'Records',
 '.',
 'Her',
 'profile',
 'received',
 'a',
 'boost',
 'after',
 'four',
 'of',
 'her',
 'songs',
 'were',
 'featured',
 'on',
 'the',
 'TV',
 'series',
 'Dawson',
 "'s",
 'Creek.Recent',
 'activity.After',
 'the',
 'renewal',
 'of',
 'her',
 'profile',
 'with',
 'Dawson',
 "'s",
 'Creek',
 ',',
 'Medley',
 'lived',
 'and',
 'worked',
 'in',
 'Los',
 'Angeles',
 ',',
 'teaching',
 'guitar',
 'and',
 'helping',
 'to',
 'develop',
 'a',
 'new',
 'generation',
 'of',
 'budding',
 'songwriters',
 'and',
 'recording',
 'artists',
 '.',
 'Medley',
 'recently',
 'returned',
 'to',
 'Canada',
 ',',
 'and',
 'is',
 'now',
 'writing',
 'and',
 'demoing',
 'new',
 'material',
 'for',
 'an',
 'upcoming',
 'release',
 '.',
 'She',
 'is',
 'currently',
 'represented',
 'by',
 'Inner',
 'Circle',
 'Management',
 ',',
 'an',
 'art',
 'and',
 'cultural',
 'industries',
 'consulting',
 'business',
 ',',
 'based',
 'in',
 'Regina',
 ',',
 'Saskatchewan',
 '.',
 'In',
 '2011',
 'she',
 'joined',
 'the',
 'horn',
 'driven',
 'band',
 'Time',
 'Well',
 'Wasted',
 'based',
 'in',
 'her',
 'home',
 'town',
 'of',
 'Courtenay',
 ',',
 'British',
 'Columbia',
 '.',
 'After',
 'two',
 'years',
 ',',
 'Medley',
 'left',
 'TWW',
 'to',
 'form',
 'her',
 'own',
 'band',
 'Sue',
 'Medley',
 '&',
 'The',
 'Back',
 'Road',
 'Band',
 ',',
 'and',
 'in',
 'July',
 '2013',
 'released',
 'the',
 '3-song',
 'EP',
 'Sue',
 'Medley',
 '&',
 'The',
 'Back',
 'Road',
 'Band',
 ',',
 'and',
 'followed',
 'this',
 'with',
 'a',
 'full',
 'length',
 'album',
 'These',
 'Are',
 'The',
 'Days',
 ',',
 'both',
 'productions',
 'co-produced',
 'with',
 'former',
 'CBC',
 'Music',
 'Producer',
 '/',
 'Recording',
 'Engineer',
 'John',
 'Mang',
 '.',
 'Sue',
 'Medley',
 'continues',
 'to',
 'perform',
 ',',
 'teach',
 'and',
 'perform',
 'in',
 'the',
 'Comox',
 'Valley',
 '.']

In [7]:
print(type(tokens[1]))
print(tokens[1])
print(type(result_wiki[0][0]))
print(result_wiki[0][0])

<class 'str'>
Medley.Susan
<class 'int'>
24031233

In [8]:
fdist = nltk.FreqDist(tokens)
fdist

FreqDist({',': 40, 'and': 25, 'the': 23, '.': 18, 'in': 16, 'of': 15, 'a': 14, 'her': 13, 'Medley': 11, 'for': 8, ...})

In [9]:
print(len(tokens))
print(len(fdist))

648
315

In [10]:
test_tokens = nltk.word_tokenize("I am a iron man and good man and I am a kind man")
test_tokens_dictionary = nltk.FreqDist(test_tokens)
test_tokens_dictionary

FreqDist({'man': 3, 'I': 2, 'am': 2, 'a': 2, 'and': 2, 'iron': 1, 'good': 1, 'kind': 1})

In [11]:
print("(term,freq)")
len(test_tokens_dictionary)
for term, freq in test_tokens_dictionary.items():
    print(term, end='')
    print(",",freq)

(term,freq)
I, 2
am, 2
a, 2
iron, 1
man, 3
and, 2
good, 1
kind, 1

In [12]:
for term, freq in fdist.items():
    print(term,",",freq)

Sue , 6
Medley.Susan , 1
Gayle , 1
Medley , 11
( , 2
born , 1
1962 , 1
at , 2
Courtenay , 2
, , 40
British , 3
Columbia , 3
) , 2
is , 3
a , 14
Canadian , 2
rock , 2
musician , 1
. , 18
She , 4
released , 5
her , 13
self-titled , 2
debut , 3
CD , 2
in , 16
1990 , 2
won , 1
Juno , 1
Award , 2
1991 , 1
for , 8
Most , 1
Promising , 1
Female , 1
Vocalist.Early , 1
years.A , 1
native , 1
of , 15
Vancouver , 1
Island , 1
Canada , 4
was , 8
signed , 1
to , 8
Polygram , 2
Records , 3
1989 , 1
and , 25
The , 8
album , 8
co-produced , 3
by , 7
John , 4
Mellencamp , 3
producer , 1
Michael , 1
Wanchic , 2
featured , 2
strong , 1
performances , 1
Hiatt , 1
's , 4
band , 3
Goners , 1
In , 3
first , 2
single , 2
Dangerous , 2
Times , 2
not , 2
only , 2
pushed , 1
gold , 1
status , 1
within , 1
few , 1
weeks , 4
release , 4
but , 1
# , 4
1 , 3
on , 8
MuchMusic , 1
two , 2
the , 23
Pop , 1
Adult , 1
charts , 1
12 , 1
Top , 1
3 , 1
national , 2
chart , 2
six , 1
earned , 1
SOCAN , 2
Songwriter , 1
Year , 1
most , 2
airplay.On , 1
heels , 1
singles , 2
Maybe , 2
Next , 2
Time , 3
Thats , 1
Life , 1
Love , 1
Thing , 1
she , 5
toured , 1
North , 1
America , 1
rest , 1
year , 1
opening , 1
Bob , 2
Dylan , 3
other , 1
high , 1
profile , 3
artists , 3
Her , 2
second , 1
Inside , 1
Out , 1
once , 1
again , 1
aided , 1
musical , 1
help , 1
slide , 1
guitarist , 1
Sonny , 1
Landreth , 1
drummer , 1
Kenny , 1
Aronoff , 1
1992 , 2
continued , 1
radio , 3
success , 1
with , 8
handful , 1
additional , 1
tours , 1
such , 1
as , 1
Tom , 1
Cochrane , 1
Kim , 1
Mitchell , 1
54.40 , 1
keeping , 1
spotlight , 1
When , 1
Stars , 1
Fall , 1
became , 1
hit , 1
reached , 1
2 , 1
being , 1
locked , 1
out , 1
U2 , 1
October , 1
invited , 1
participate , 1
Tribute , 1
Madison , 1
Square , 1
Gardens , 1
New , 1
York , 1
City , 1
performed , 1
duet , 1
classic , 1
track , 1
Like , 1
Rolling , 1
Stone , 1
Later , 1
that , 4
month , 1
received , 2
award , 1
song , 1
which , 2
one , 1
played , 1
songs , 3
1991.Dispute , 1
Polygram.Her , 1
third , 1
however , 1
would , 2
be , 1
forthcoming , 1
Following , 1
two-year , 1
dispute , 1
record , 1
label , 1
over , 1
comprise , 1
parted , 1
ways , 1
retreated , 1
house , 1
near , 1
Bloomington , 1
Indiana , 1
wrote , 1
recorded , 1
much , 1
material , 2
made , 1
up , 1
independent , 1
Velvet , 1
Morning , 1
February , 1
2000 , 1
Egg , 1
boost , 1
after , 1
four , 1
were , 1
TV , 1
series , 1
Dawson , 2
Creek.Recent , 1
activity.After , 1
renewal , 1
Creek , 1
lived , 1
worked , 1
Los , 1
Angeles , 1
teaching , 1
guitar , 1
helping , 1
develop , 1
new , 2
generation , 1
budding , 1
songwriters , 1
recording , 1
recently , 1
returned , 1
now , 1
writing , 1
demoing , 1
an , 2
upcoming , 1
currently , 1
represented , 1
Inner , 1
Circle , 1
Management , 1
art , 1
cultural , 1
industries , 1
consulting , 1
business , 1
based , 2
Regina , 1
Saskatchewan , 1
2011 , 1
joined , 1
horn , 1
driven , 1
Well , 1
Wasted , 1
home , 1
town , 1
After , 1
years , 1
left , 1
TWW , 1
form , 1
own , 1
& , 2
Back , 2
Road , 2
Band , 2
July , 1
2013 , 1
3-song , 1
EP , 1
followed , 1
this , 1
full , 1
length , 1
These , 1
Are , 1
Days , 1
both , 1
productions , 1
former , 1
CBC , 1
Music , 1
Producer , 1
/ , 1
Recording , 1
Engineer , 1
Mang , 1
continues , 1
perform , 2
teach , 1
Comox , 1
Valley , 1

In [13]:
# sql = "create table InvertedIndex (term varchar(255) not null, id int(11) not null, freq int(11) not null)"
# cursor.execute(sql)

InternalError: (1050, "Table 'InvertedIndex' already exists")

In [14]:
import pymysql.cursors
import pandas as pd
pd.read_sql("show tables",con)

  Tables_in_swyoo
0   InvertedIndex
1            link
2            wiki

In [45]:
sql = "insert into InvertedIndex (term,id,freq) values (%s,%s,%s)"
cursor.execute(sql,('test',1360,1))
con.commit()

In [41]:
sql = "insert into InvertedIndex (term,id,freq) values (%s,%s,%s)"
cursor.execute(sql,('test',1346,1))
con.commit()

In [48]:
sql = "select * from InvertedIndex"
pd.read_sql(sql,con)

Empty DataFrame
Columns: [term, id, freq]
Index: []

In [43]:
sql = "delete from InvertedIndex where id = %s"
cursor.execute(sql,1360)

2

In [46]:
sql = "delete from InvertedIndex"
cursor.execute(sql)

2

In [50]:
sql = "select * from InvertedIndex"
pd.read_sql(sql,con)

Empty DataFrame
Columns: [term, id, freq]
Index: []

In [52]:
test_tokens_dictionary

FreqDist({'man': 3, 'I': 2, 'am': 2, 'a': 2, 'and': 2, 'iron': 1, 'good': 1, 'kind': 1})

In [53]:
sql = "insert into InvertedIndex (term,id,freq) values (%s,%s,%s)"
for term, freq in test_tokens_dictionary.items():
    cursor.execute(sql,(term, result_wiki[0][0] , freq))
con.commit()
sql = "select * from InvertedIndex"
pd.read_sql(sql,con)

   term        id  freq
0     I  24031233     2
1    am  24031233     2
2     a  24031233     2
3  iron  24031233     1
4   man  24031233     3
5   and  24031233     2
6  good  24031233     1
7  kind  24031233     1

In [65]:
result_wiki[0][2]

"Sue Medley.Susan Gayle Sue Medley (born 1962 at Courtenay, British Columbia) is a Canadian rock musician. She released her self-titled debut CD in 1990. She won a Juno Award in 1991 for Most Promising Female Vocalist.Early years.A native of Vancouver Island, British Columbia, Canada, Sue Medley was signed to Polygram Records Canada in 1989 and released a self-titled debut CD in 1990. The album was co-produced by Medley and John Mellencamp producer Michael Wanchic and featured strong performances by John Hiatt's band The Goners. In Canada Medley's first single, Dangerous Times not only pushed her debut album to gold status within a few weeks of release, but was #1 on MuchMusic for two weeks, #1 on the Pop Adult charts for 12 weeks, in the Top 3 of the national album rock chart for six weeks, and earned her a SOCAN Songwriter of the Year Award for most airplay.On the heels of the singles Dangerous Times, Maybe the Next Time, Thats Life, and Love Thing, she toured North America the rest of the year opening for Bob Dylan and other high profile artists. Her second album, Inside Out, was once again co-produced by Medley and Wanchic and was aided by the musical help of slide guitarist Sonny Landreth and drummer Kenny Aronoff. The album, released in 1992, continued her radio success with a handful of additional singles and national tours with such artists as Tom Cochrane, Kim Mitchell and 54.40, keeping her in the spotlight. The first single When the Stars Fall became a hit on album radio and reached #2 on The Records chart (being locked out of #1 only by U2). In October 1992 she was invited by John Mellencamp to participate in the Bob Dylan Tribute at Madison Square Gardens in New York City, and performed a duet with Mellencamp on the classic Dylan track Like a Rolling Stone. Later that month she received a SOCAN award for her song Maybe the Next Time, which was one of the most played songs on Canadian radio in 1991.Dispute with Polygram.Her third album, however, would not be forthcoming. Following a two-year dispute with her record label over the songs that would comprise that release, she and Polygram parted ways. She retreated to her house near Bloomington, Indiana, and wrote and recorded much of the material that made up her independent release, Velvet Morning, which was released in February 2000 on Egg Records. Her profile received a boost after four of her songs were featured on the TV series Dawson's Creek.Recent activity.After the renewal of her profile with Dawson's Creek, Medley lived and worked in Los Angeles, teaching guitar and helping to develop a new generation of budding songwriters and recording artists. Medley recently returned to Canada, and is now writing and demoing new material for an upcoming release. She is currently represented by Inner Circle Management, an art and cultural industries consulting business, based in Regina, Saskatchewan. In 2011 she joined the horn driven band Time Well Wasted based in her home town of Courtenay, British Columbia. After two years, Medley left TWW to form her own band Sue Medley & The Back Road Band, and in July 2013 released the 3-song EP Sue Medley & The Back Road Band, and followed this with a full length album These Are The Days, both productions co-produced with former CBC Music Producer / Recording Engineer John Mang. Sue Medley continues to perform, teach and perform in the Comox Valley."

In [74]:
# test tokenization 
tokens = nltk.word_tokenize(result_wiki[0][2].lower())
fdist = nltk.FreqDist(tokens)
print(fdist['man'])

0

In [54]:
# con.close()